FROM nvidia_noetic:latest

# Change the default shell to Bash
SHELL [ "/bin/bash" , "-c" ]

# Install build essential for C/C++ Compilers
RUN apt-get update && apt-get install -y build-essential cmake

# Install Git
RUN apt-get update && apt-get install -y git

# Install additional ROS dependecies
RUN apt-get update \
    && apt install -y ros-noetic-realsense2-description \
    && apt install -y ros-noetic-ros-control ros-noetic-ros-controllers \
    && apt install -y ros-noetic-xacro \
    && apt install -y ros-noetic-moveit

# Install pip for Python 3.8
RUN apt-get update \
    && apt-get install -y python3-pip python3.8-distutils \
    && python3.8 -m pip install --upgrade pip \
    && apt-get install -y python3-tk

# Install needed Python libraries 
COPY requirements.txt /requirements.txt
RUN python3.8 -m pip install --ignore-installed -r /requirements.txt \
    && rm /requirements.txt

# Create the catkin workspace
RUN source /opt/ros/noetic/setup.bash \
    && mkdir -p /catkin_ws/src \
    && cd /catkin_ws/src \
    && catkin_init_workspace

# Copy entrypoint script for launching ROS
COPY docker/entrypoint.sh /catkin_ws/

# Setup working directory on startup
WORKDIR /catkin_ws 

ENTRYPOINT [ "/catkin_ws/entrypoint.sh" ]